title: Jordan Bell Mathematics
author:
  name: Jordan Bell
  email: jordan.bell@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Jordan Bell Mathematics

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    github:  jordanbell2357
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: jordanbell2357
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - tutoring.md
 - exercises.md
 - philosophy.md
 - links.md
 - expository.md
 - publications.md
 - visualizations.md
 - projects.md
 - CV.md


# Build settings
markdown: kramdown
kramdown:
 math_engine: mathjax

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
collections:
  quotes:
    output: true